In [2]:
import nsfg
import pandas as pd

In [3]:
preg = nsfg.ReadFemPreg()

In [4]:
preg.head()

,caseid,pregordr,howpreg_n,howpreg_p,moscurrp,nowprgdk,pregend1,pregend2,nbrnaliv,multbrth,...,laborfor_i,religion_i,metro_i,basewgt,adj_mod_basewgt,finalwgt,secu_p,sest,cmintvw,totalwgt_lb
0,1,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3410.389399,3869.349602,6448.271112,2,9,NaN,8.8125
1,1,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3410.389399,3869.349602,6448.271112,2,9,NaN,7.8750
2,2,1,NaN,NaN,NaN,NaN,5.0,NaN,3.0,5.0,...,0,0,0,7226.301740,8567.549110,12999.542264,2,12,NaN,9.1250
3,2,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,7226.301740,8567.549110,12999.542264,2,12,NaN,7.0000
4,2,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,7226.301740,8567.549110,12999.542264,2,12,NaN,6.1875

In [5]:
resp = nsfg.ReadFemResp()

In [6]:
resp.head()

,caseid,rscrinf,rdormres,rostscrn,rscreenhisp,rscreenrace,age_a,age_r,cmbirth,agescrn,...,pubassis_i,basewgt,adj_mod_basewgt,finalwgt,secu_r,sest,cmintvw,cmlstyr,screentime,intvlngth
0,2298,1,5,5,1,5.0,27,27,902,27,...,0,3247.916977,5123.759559,5556.717241,2,18,1234,1222,18:26:36,110.492667
1,5012,1,5,1,5,5.0,42,42,718,42,...,0,2335.279149,2846.799490,4744.191350,2,18,1233,1221,16:30:59,64.294000
2,11586,1,5,1,5,5.0,43,43,708,43,...,0,2335.279149,2846.799490,4744.191350,2,18,1234,1222,18:19:09,75.149167
3,6794,5,5,4,1,5.0,15,15,1042,15,...,0,3783.152221,5071.464231,5923.977368,2,18,1234,1222,15:54:43,28.642833
4,616,1,5,4,1,5.0,20,20,991,20,...,0,5341.329968,6437.335772,7229.128072,2,18,1233,1221,14:19:44,69.502667

In [7]:
resp.pregnum.head()

0    4
1    1
2    1
3    0
4    0
Name: pregnum, dtype: int64

In [8]:
preg_map = nsfg.MakePregMap(preg)
preg_map_head = nsfg.MakePregMap(preg.head(10))
print(preg_map_head)
for caseid, indices in preg_map_head.items():
    print(caseid, len(indices))

defaultdict(<class 'list'>, {1: [0, 1], 2: [2, 3, 4], 6: [5, 6, 7], 7: [8, 9]})
1 2
2 3
6 3
7 2

In [9]:
preg_map[1]

[0, 1]

In [10]:
indices1 = preg_map[1]
print(len(indices1))
print(len(preg_map[1]))

2
2

In [11]:
resp.pregnum[resp.caseid == 1].item()

2

In [20]:
c_id_resp = resp.set_index('caseid').pregnum.sort_index()
c_id_resp.head()

caseid
1    2
2    3
4    0
6    3
7    2
Name: pregnum, dtype: int64

In [58]:
def test():

    for c_id, indices in preg_map.items():
        if resp.pregnum[resp.caseid == c_id].item() != len(indices):
            print(f"error caseid: {c_id}")
            return False
    return True

answer = test()
answer

True